version: '3.8'
 
services:
  api:
    build: .
    container_name: "api"
    restart: always
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      DEBUG: 1
 
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
    container_name: "db"
 
volumes:
    postgres_data:
 